import { Maven_Pro } from 'next/font/google'
import '../globals.css'

export const metadata = {
  title: 'Autenticação',
  description: 'Generated by Next.js',
}

const maven = Maven_Pro({
  weight: ['400', '600', '900'],
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={maven.className}>
        {children}</body>
    </html>
  )
}
