import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import '../globals.css'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/providers/auth'
import Footer from '@/components/ui/footer'
import CartProvider from '@/providers/cart'

import { Toaster } from "@/components/ui/toaster"
import HeaderAdmin from '@/components/ui/header-admin'
import Sidebar from '@/components/sidebar'
import AdminProvider from '@/providers/admin'

const maven = Maven_Pro({
  weight: ['400', '600', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'SW Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={maven.className}>
        <div className='flex h-full flex-col'>
          <AuthProvider>
            <AdminProvider>
              <div className="flex h-full w-full">
                <Sidebar />
                <div className='flex flex-col w-full h-full min-h-full bg-accent'>
                  <HeaderAdmin />
                  <main className='flex flex-1 w-full items-center p-8 overflow-hidden max-md:p-4 max-md:overflow-y-auto'>
                    {children}
                  </main>
                </div>
              </div>
              <Toaster />
            </AdminProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
