import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import '../globals.css'
import Header from '@/components/ui/header'
import { AuthProvider } from '@/providers/auth'
import Footer from '@/components/ui/footer'
import CartProvider from '@/providers/cart'

import { Toaster } from "@/components/ui/toaster"
import HeaderAdmin from '@/components/ui/header-admin'
import Sidebar from '@/components/sidebar'

const maven = Maven_Pro({
  weight: ['400', '600', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'SW Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={maven.className}>
        <div className='flex h-full flex-col'>
          <AuthProvider>
            <div className="flex h-full w-full">
              <Sidebar />
              <div className='flex flex-col w-full h-full min-h-full bg-accent'>
                <HeaderAdmin />
                <main className='flex flex-1 p-8'>
                  {children}
                </main>
              </div>
            </div>
            <Toaster />
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
